export const queryKeys = {
  auth: ['auth', 'me'] as const,
  tools: ['tools'] as const,
  savedRuns: (userId: string) => ['me', 'tool-runs', userId] as const,
  savedRun: (userId: string, id: string) => ['me', 'tool-runs', userId, id] as const,
  templates: (userId: string) => ['me', 'templates', userId] as const,
  template: (userId: string, id: string) => ['me', 'templates', userId, id] as const,
  bookmarks: (userId: string) => ['me', 'bookmarks', userId] as const,
  adminArticles: ['admin', 'articles'] as const,
  adminArticle: (id: string) => ['admin', 'articles', id] as const,
  adminCourses: ['admin', 'courses'] as const,
  adminCourse: (id: string) => ['admin', 'courses', id] as const,
  articles: ['articles'] as const,
  article: (slug: string) => ['articles', slug] as const,
  courses: ['courses'] as const,
  course: (slug: string) => ['courses', slug] as const,
  lesson: (slug: string) => ['lessons', slug] as const,
  discussions: ['discussions'] as const,
  discussion: (slug: string) => ['discussions', slug] as const,
};
